#ifndef _IPOD_AUDIO_H_
#define _IPOD_AUDIO_H_

typedef enum {
	PS_PAUSED,
	PS_PLAY,
	PS_FFREW,
	PLAYSTATUS_MAX,
} IPOD_PLAY_STATUS;

typedef enum {
	PLAYBACK_STATE_STOP,
	PLAYBACK_STATE_PLAY,
	PLAYBACK_STATE_PAUSED,
	PLAYBACK_STATE_FF,
	PLAYBACK_STATE_REW,
	PLAYBACK_STATE_MAX,
} PLAYBACK_STATE;

typedef enum {
	PLAYER_NONE,
	PLAYER_DISCONNECTED,
	PLAYER_CONNECTING,
	PLAYER_DISCONNECTING,
	PLAYER_CONNECTED,
	PLAYER_INITIALIZED,
	PLAYER_STATE_MAX
} PLAYER_STATE;

typedef enum {
	//IPODUI_BRWS_SELECT_ALL,
	IPODUI_BRWS_GENRE,
	IPODUI_BRWS_ARTIST,
	IPODUI_BRWS_ALBUM,
	IPODUI_BRWS_TRACK,
	//IPODUI_BRWS_PLAYLIST,
	IPODUI_BRWS_MAX
} IPODUI_BRWS_CATEGORYTYPE;


extern BOOL iPod_GetAudioThreadStatus(VOID);
extern BOOL iPod_StartAudioThread(VOID);
extern VOID iPod_StopAudioThread(VOID);
extern VOID iPod_CloseAudioThread(VOID);

extern VOID iPod_AudioStart(VOID);
extern VOID iPod_AudioStop(VOID);

extern VOID iPod_SetAudioSamplingFreq(DWORD nSamplingFreq);

#endif	// _IPOD_AUDIO_H_
